config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  get '/', to: 'pages#home'

  get '/users', to: 'users#index', as: 'users'
  get '/signup', to: 'users#new', as: 'signup'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/profile', to: 'users#show', as: 'profile'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update'
  get '/users/:id/delete_team', to: 'users#delete_team', as: 'delete_team'
  post '/users/admin', to: 'users#create_admin'

  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy'
  post '/sessions', to: 'sessions#create'

  get '/events', to: 'events#index', as: 'events'
  get '/events/new', to: 'events#new', as: 'new_event'
  post '/events', to:'events#create'
  get '/events/:id', to: 'events#show', as: 'event'
  get '/events/:id/edit', to: 'events#edit', as: 'edit_event'
  patch '/events/:id', to: 'events#update'

  get '/users/:user_id/pokemons', to: 'pokemons#index'
  get '/users/:user_id/pokemons/:id', to: 'pokemons#show', as: 'pokemon'
  get '/catch/:hash_data', to: 'pokemons#new', as: 'catch'
  post '/catch', to: 'pokemons#create'
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :pokemons
	has_secure_password

	def self.confirm(params)
		@user = User.find_by({username: params[:username]})
		@user.try(:authenticate, params[:password])
	end

	#TODO: move any db calls and repetitive code from the resepective controllers to the models and make them methods. We love fat models. -jc

	validates :full_name, :email, :password, presence: true, length: {maximum: 255}
	validates :username, length: {in: 6..50, message: "must be between 6 and 50 characters"}
	validates :password, length: { minimum: 3, message: "must be at least 3 characters" }
	validates :email, :username, uniqueness: true

	validates :email, format: { with: /@/ }, length: { minimum: 6 }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in?, :set_user, only: [:show, :edit, :update, :delete_team]

	def index
		if admin?
			@users = User.where(admin: true)
			@user = User.new
		else
			redirect_to events_path
		end
	end

	def create_admin
		if admin?
			# Find the user going to be admin by username
			user = User.find_by(username: params[:username])
			if user
				# Update the admin attribute by the opposite
				user.update_attribute(:admin, !user.admin)
				if user.admin
					flash[:notice] = 'Successfully added admin.'
				else
					flash[:notice] = 'Successfully removed admin.'
				end
			else
				flash[:error] = 'User not found, please try again.'
			end
			redirect_to users_path
		else
			redirect_to events_path
		end
	end


	def new
		@user = User.new
	end

	def create
		user_params = params.require(:user).permit(:full_name, :username, :email, :password)
		@user = User.new(user_params)
		if @user.save
			flash[:notice] = "Successfully created account!"
			login(@user)
			if session[:catch_data]
				redirect_to catch_path(session[:catch_data])
				session[:catch_data] = nil
			else
				redirect_to events_path
			end
		else
			flash[:error] = @user.errors.full_messages.join(", ")
			redirect_to signup_path
		end
	end

	def show
		# TODO: consider adding the below code to your User model as a method
		# Find all the pokemons for the user
		@pokemons = @user.pokemons
		# Select pokemon in the team
		@team = @pokemons
			.select { |poke| poke.team_position }
			.sort_by { |x| x.team_position }
	end

	def edit
		# TODO: consider adding the below code to your User model as a method
		if @user == current_user
		@pokemons = @user.pokemons
		@team = @pokemons
			.select { |poke| poke.team_position }
			.sort_by { |x| x.team_position }
		else
			redirect_to @user
		end
	end

	def update
		# Set pkoe1 to the pokemon selete from team or use the empty id
		# TODO: consider adding the below db call to your User model as a method
		poke1 = Pokemon.find_by_id(params[:team_poke]) || params[:empty_position]
		poke2 = Pokemon.find_by_id(params[:backpack_poke])

		# If empty id is selete
		if params[:empty_position]
			poke2.team_position = poke1
			if poke2.save
				respond_to do |format|
					format.json { head :ok } # response success for ajax
				end
			end
		else
			# Swap the opsition
			poke2.team_position = poke1.team_position
			poke1.team_position = nil
			if poke1.save && poke2.save
				respond_to do |format|
					format.json { head :ok }
				end
			end
		end
	end

	def delete_team
		# Clear team by set position to nil in all pokemons
		@user.pokemons.each do |pokemon|
			pokemon.team_position = nil
			pokemon.save
		end
		redirect_to edit_user_path(current_user)
	end

	private

	def set_user
		user_id = params[:id] || current_user.id
		@user = User.find_by_id(user_id)
	end

end

app/helpers/users_helper.rb
module UsersHelper

  def admin?
    current_user.try(:admin)
  end

end

app/views/users/edit.html.erb
<p hidden id="user_id"><%= @user.id%></p>

<div class="container centered">
	<h2>My Team </h2>
	<div id='my_team'>
		<div class='row'>
			<% @team.each do |pokemon| %>
				<div class='poke col-sm-2 col-xs-4' data-id=<%= pokemon.id%>>
					<%= image_tag pokemon.event.image, size: "100" %><br>
						<p><%= pokemon.event.name %></p>

				</div>
			<% end %>
			<% (@team.size+1..6).each do |n| %>
				<div class='poke col-sm-2 col-xs-4' data-empty-id=<%= n %>>
					<%= image_tag "", size: "100" %><br>
						<p>Empty</p>
				</div>
			<% end %>
		</div>

	</div>
	<div class="centered"><%= link_to "Clear Team", delete_team_path, id: "delete", class: "btn btn-danger"%>
	</div>
</div>
<hr />

<div class='container centered'>

	<h2>My Back Pack</h2>
	<div>
		<%= link_to "Back", user_path(current_user), class: "btn btn-primary" %>
	  <%= button_tag "Save Team", class: "btn btn-success", id: "save" %>
	</div>

	<div id="my_backpack"class="container">
		<% @pokemons.each do |pokemon| %>
			<% if !pokemon.team_position %>
				<div class='poke col-sm-2 col-xs-3' data-id=<%= pokemon.id%>>
	        <%= image_tag pokemon.event.image, size: "100" %><br>
						<p><%= pokemon.event.name %></p>
				</div>
			<% end %>
		<%end%>
	</div>
</div>

app/views/users/index.html.erb
<p>There are <%= @users.count %> users signed up here.</p>
<div class="container">

<%= form_tag('/users/admin', method: 'post') do %>
<%= label_tag(:username, "User Name")%>
<%= text_field_tag(:username)%>
<%= submit_tag('Save/Remove Admin')%>
<% end %>

  
  <% @users.each do |user| %>

  <div id="<%= user.username %>" class="admin col-sm-2" data-id="<%= user.id %>">
    <h4><%= user.full_name %></h4>
    <p><strong>Username: </strong> <%= user.username %></p>
    <p><strong>User Email: </strong><%= user.email %></p>
     <hr>
    </div>
  <% end %>
  
</div>

app/views/users/new.html.erb
<section id='signup-form' class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <%= form_for @user do |f| %>
        <fieldset>
          <legend>Signup</legend>

          <div class="form-group">
            <label class="col-md-4 control-label" for="full_name">Full name:</label>
            <div class="col-md-8">
              <%= f.text_field :full_name, required: true, placeholder: "John Doe", class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="username">Username:</label>
            <div class="col-md-8">
              <%= f.text_field :username, required: true, placeholder: "user123", class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="email">Email address:</label>
            <div class="col-md-8">
              <%= f.text_field :email, required: true, placeholder: "name@example.com", class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="password">Password</label>
            <div class="col-md-8">
              <%= f.password_field :password, required: true, placeholder: "Password", class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <div class="col-md-12">
              <%= f.submit "Sign up", class: "btn btn-success" %>
            </div>
          </div>

        </fieldset>
      <% end %>

    </div>
  </div>
</section>

app/views/users/show.html.erb
<div class='users centered'>
	<div class='container'>

		<h1>Welcome <%= @user.username %></h1>
		<p><%= @user.email %></p>

		<p class="small text-muted">Joined <%= time_ago_in_words(@user.created_at) %> ago</p>
		<% if @current_user == @user %>
			<%= link_to "Edit Team", edit_user_path(current_user), class: "btn btn-success" %>
		<% end %>

	</div>
	<div class='container'>
		<h2>My Team</h2>
		<div id='my_team'>
			<div class='row'>
				<% @team.each do |pokemon| %>
					<div class='col-sm-2 col-xs-4'>
						<%= link_to image_tag(pokemon.event.image, size: "100"), pokemon_path(@user, pokemon) %><br>
						<p><%= pokemon.event.name %></p>
					</div>
				<% end %>
				<% (@team.size+1..6).each do |n| %>
					<div class='col-sm-2 col-xs-4'>
						<%= image_tag "", size: "100"%><br>
						<p>Empty</p>
					</div>
				<% end %>
			</div>
		</div>
	</div>
	<hr>

	<div class="container">
		<h2>My Back Pack</h2>
		<div id="my_backpack">
			<div class="row">

				<% @pokemons.each do |pokemon| %>
					<% if !pokemon.team_position %>
						<div class='col-sm-2 col-xs-3'>
							<%= link_to image_tag(pokemon.event.image, size: "100"), pokemon_path(@user, pokemon) %><br>
							<p><%= pokemon.event.name %></p>
						</div>
					<% end %>
				<%end%>

			</div>
		</div>
	</div>
</div>