config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  get '/', to: 'pages#home'

  get '/users', to: 'users#index', as: 'users'
  get '/signup', to: 'users#new', as: 'signup'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/profile', to: 'users#show', as: 'profile'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update'
  get '/users/:id/delete_team', to: 'users#delete_team', as: 'delete_team'
  post '/users/admin', to: 'users#create_admin'

  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy'
  post '/sessions', to: 'sessions#create'

  get '/events', to: 'events#index', as: 'events'
  get '/events/new', to: 'events#new', as: 'new_event'
  post '/events', to:'events#create'
  get '/events/:id', to: 'events#show', as: 'event'
  get '/events/:id/edit', to: 'events#edit', as: 'edit_event'
  patch '/events/:id', to: 'events#update'

  get '/users/:user_id/pokemons', to: 'pokemons#index'
  get '/users/:user_id/pokemons/:id', to: 'pokemons#show', as: 'pokemon'
  get '/catch/:hash_data', to: 'pokemons#new', as: 'catch'
  post '/catch', to: 'pokemons#create'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GottaCacheEmAll</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS'] %>"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="/"><img class ="navIcon" src ="/images/pikachusprite.gif" href ='/'><a class="navbar-brand">Gotta Cache 'Em All</a>
        <button class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Events", events_path %></li>
          <% if current_user %>
            <li><%= link_to "Profile", profile_path, id: "profile_link"  %></li>
            <% if admin? %>
              <li><%= link_to "Administrators", users_path, id: 'admin_link' %></li>
            <% end %>
            <li><%= link_to "Logout", logout_path, id: "logout_link"  %></li>
          <% else %>
            <li><%= link_to "Sign Up", signup_path, id: "signup_link" %></li>
            <li><%= link_to "Login", login_path, id: "login_link" %></li>
          <% end %>

        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

	<% flash.each do |name, msg| %>
    <% if name == "error" %>
  	  <p class="alert-danger">
    <% else %>
      <p class="alert-success">
    <% end %>
	    <small> <%= name.capitalize %>: <%= msg %> </small>
	  </p>
	<% end %>

	<%= yield %>

</body>
</html>

app/views/layouts/pokemon.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GottaCacheEmAll</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS'] %>"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="/"><img class ="navIcon" src ="/images/pikachusprite.gif" href ='/'><a class="navbar-brand">Gotta Cache 'Em All</a>
        <button class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Events", events_path %></li>
          <% if current_user %>
            <li><%= link_to "Profile", profile_path, id: "profile_link"  %></li>
            <% if admin? %>
              <li><%= link_to "Administrators", users_path, id: 'admin_link' %></li>
            <% end %>
            <li><%= link_to "Logout", logout_path, id: "logout_link"  %></li>
          <% else %>
            <li><%= link_to "Sign Up", signup_path, id: "signup_link" %></li>
            <li><%= link_to "Login", login_path, id: "login_link" %></li>
          <% end %>

        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

	<% flash.each do |name, msg| %>
    <% if name == "error" %>
  	  <p class="alert-danger">
    <% else %>
      <p class="alert-success">
    <% end %>
	    <small> <%= name.capitalize %>: <%= msg %> </small>
	  </p>
	<% end %>

	<%= yield %>

</body>
</html>